export const ANGLE_BANK: { theme: string; angle: string; fits: string }[] = [
  { theme: "food-noise", angle: "I used to plan my day around where the nearest bathroom was — here's the boring two-ingredient dinner I eat now.", fits: "gut" },
  { theme: "myth-flip", angle: "Everyone told me I needed more fiber; in my experience my gut got quieter when I stopped forcing it — opinion, but I'm sticking with it.", fits: "gut" },
  { theme: "what-I-eat", angle: "A full day of eating with a stomach that used to hate everything: three foods, zero drama.", fits: "gut" },
  { theme: "simplicity", angle: "I stopped eating 40 ingredients a day and the after-dinner bloat stopped showing up — simplest experiment I've ever run on myself.", fits: "gut" },
  { theme: "adaptation", angle: "Week one felt rough; week three my jeans stopped digging into a bloated stomach — my honest timeline, nobody else's.", fits: "gut" },
  { theme: "social", angle: "What I tell waiters so I don't spend the drive home regretting dinner: my exact steakhouse order.", fits: "gut" },
  { theme: "transformation-feel", angle: "I forgot what it felt like to finish a meal and just… feel fine. That's the whole post.", fits: "gut" },
  { theme: "Q&A", angle: "'Don't you miss bread?' Honestly — I don't miss how bread made me feel.", fits: "gut" },
  { theme: "cooking", angle: "The 10-minute ground beef bowl I make when my stomach wants zero surprises.", fits: "gut" },
  { theme: "myth-flip", angle: "Hot take from my own kitchen: 'balanced' eating left me bloated for years; boring eating gave me my evenings back.", fits: "gut" },
  { theme: "transformation-feel", angle: "3pm used to knock me out at my desk; now I forget to make the second coffee — here's what changed at lunch.", fits: "energy" },
  { theme: "what-I-eat", angle: "What I eat on a workday now that I'm done crashing at my desk: two plates, no snacks, no drama.", fits: "energy" },
  { theme: "myth-flip", angle: "I ate 'heart-healthy' cereal for 20 years and dragged myself to work — my opinion: steak and eggs won.", fits: "energy" },
  { theme: "adaptation", angle: "The first ten days I was tired and salty (literally) — then my mornings flipped. My honest week-by-week.", fits: "energy" },
  { theme: "simplicity", angle: "I deleted breakfast as a decision: same plate every morning, and my afternoons feel younger than my 30s did.", fits: "energy" },
  { theme: "routine", angle: "Dad, full-time job, zero patience for meal prep: my entire Sunday prep is 20 minutes. Here's the plate.", fits: "energy" },
  { theme: "Q&A", angle: "'Isn't eating the same thing boring?' My honest answer after a year: boring is exactly why it works for me.", fits: "energy" },
  { theme: "satiety", angle: "I used to graze from 8pm till bed. Now I eat dinner and I'm just… done. Still weirds me out.", fits: "energy" },
  { theme: "myth-flip", angle: "Snacks were 'keeping my metabolism going,' they said. Dropping them is when my afternoons came back — take it or leave it.", fits: "energy" },
  { theme: "transformation-feel", angle: "I'm 45 and I stopped dreading the stairs after leg day — here's what my meals look like now.", fits: "energy" },
  { theme: "transformation-feel", angle: "I'm 52 and I stopped waking up at 3am wired-and-tired — the supper swap I tried first.", fits: "midlife-women" },
  { theme: "what-I-eat", angle: "What I eat in a day at 48, after decades of 1,200-calorie rules that left me starving and stuck in the same place.", fits: "midlife-women" },
  { theme: "myth-flip", angle: "I did low-fat through my entire 30s and was hungry for a decade — contrarian take from my own kitchen: the butter stays.", fits: "midlife-women" },
  { theme: "satiety", angle: "The 4pm 'eat everything in the pantry' spiral just… stopped for me. Here's the lunch I changed.", fits: "midlife-women" },
  { theme: "simplicity", angle: "Midlife scrambled a lot of things; my grocery list is the one thing I made simple. Five items, every week.", fits: "midlife-women" },
  { theme: "social", angle: "What I actually eat at book club so nobody makes it A Thing — and neither do I.", fits: "midlife-women" },
  { theme: "Q&A", angle: "'Where do you get your energy?' my daughter asked, unironically, while I carried the groceries. My honest answer.", fits: "midlife-women" },
  { theme: "adaptation", angle: "Week one I doubted everything. Week four I gave away my afternoon coffee. An honest midlife diary.", fits: "midlife-women" },
  { theme: "transformation-feel", angle: "My cravings didn't need more willpower — they needed a different plate. Opinion from my own kitchen at 50.", fits: "midlife-women" },
  { theme: "routine", angle: "Fifty-something and my 'diet' is one pan and salt — the least complicated my food has been since childhood.", fits: "midlife-women" },
  { theme: "transformation-feel", angle: "I stopped cropping my skin out of photos this year — here's the boring food routine behind it, my experience only.", fits: "skin" },
  { theme: "what-I-eat", angle: "What I eat in a day as someone whose skin used to be the first thing I checked every morning.", fits: "skin" },
  { theme: "myth-flip", angle: "I dropped the 'glow' smoothies and my skin looked calmer within months — unpopular opinion: my face likes steak.", fits: "skin" },
  { theme: "simplicity", angle: "Three-item grocery list, one pan, and the calmest my skin has looked in years — n of 1, but it's my n.", fits: "skin" },
  { theme: "Q&A", angle: "'What's your skincare routine?' It's shorter than you think — and it starts in the kitchen. Just my experience.", fits: "skin" },
  { theme: "adaptation", angle: "My skin looked worse before it looked better that first month — nobody warned me, so I'm warning past-me.", fits: "skin" },
  { theme: "routine", angle: "Morning: eggs. Evening: beef. My bathroom shelf has never been emptier — coincidence? Maybe. It's still my routine.", fits: "skin" },
  { theme: "cooking", angle: "Tallow in the pan, not just in the moisturizer — the fatty cuts I stopped fearing, and my face didn't complain.", fits: "skin" },
  { theme: "transformation-feel", angle: "A year of makeup-free Mondays I never thought I'd post. Food was my variable — not advice, just my story.", fits: "skin" },
  { theme: "social", angle: "People ask what I 'use' for my skin and never expect the answer to be 'a cast-iron pan.' My honest routine.", fits: "skin" },
  { theme: "grocery-haul", angle: "Feeding four on ground beef and eggs: our $120 weekly haul, and not one box in the cart.", fits: "budget-family" },
  { theme: "budget", angle: "$3 dinners, one pan, zero 'what's for dinner' fights — the default plate that saved our weeknights.", fits: "budget-family" },
  { theme: "myth-flip", angle: "'Meat is expensive' — my receipts disagreed once I dropped the snacks, sauces, and cereal. Opinion, with my own math.", fits: "budget-family" },
  { theme: "cooking", angle: "Chuck roast Sunday: one cheap cut, three family dinners — exactly how we stretch it.", fits: "budget-family" },
  { theme: "what-I-eat", angle: "Family dinner since we simplified: meat, eggs, butter — and weirdly fewer bedtime snack negotiations.", fits: "budget-family" },
  { theme: "grocery-haul", angle: "We stopped shopping the middle aisles entirely; our cart is 90% the meat counter. Weekly haul, prices on screen.", fits: "budget-family" },
  { theme: "Q&A", angle: "'Isn't feeding a family like this complicated?' We cook one protein in one pan most nights. That's the whole answer.", fits: "budget-family" },
  { theme: "simplicity", angle: "Meal planning used to eat my Sunday; now it's 'which meat is on sale.' Our entire system in 30 seconds.", fits: "budget-family" },
  { theme: "budget", angle: "Eggs carried our budget this month — five family meals under $2 a plate, my receipts on screen.", fits: "budget-family" },
  { theme: "social", angle: "Grandma still thinks we're nuts; the kids still ask for seconds. A holiday dinner at our carnivore-ish table.", fits: "budget-family" },
  { theme: "travel", angle: "Gas station dinner without the regret: what I actually grab at a pump stop — jerky, eggs, a tin of fish, done.", fits: "on-the-road" },
  { theme: "travel", angle: "My cooler is my meal plan: 14-hour drive, zero drive-thru stops — here's what's inside.", fits: "on-the-road" },
  { theme: "Q&A", angle: "'What do you even eat on the road?' A week of hotel-room dinners with nothing but a kettle and a cooler.", fits: "on-the-road" },
  { theme: "myth-flip", angle: "They say eating clean on the road is impossible. After 100k miles, my take: it's easier than eating 'balanced' at a truck stop.", fits: "on-the-road" },
  { theme: "what-I-eat", angle: "Day of eating from the driver's seat: what I pack, what I buy, what I skip — no kitchen required.", fits: "on-the-road" },
  { theme: "simplicity", angle: "I stopped needing a microwave, a fridge, or a menu. Road food got simple the day my food got simple.", fits: "on-the-road" },
  { theme: "cooking", angle: "The steakhouse script for road eaters: 'ribeye, butter, no sauce' — my exact order anywhere in America.", fits: "on-the-road" },
  { theme: "transformation-feel", angle: "I used to roll onto the job site bloated and wrecked from drive-thru food; now I show up and just work. My fix fits in a lunchbox.", fits: "on-the-road" },
  { theme: "budget", angle: "Canned fish is my road cheat code — pocket change a tin, and I'm not starving at the counter by 6pm.", fits: "on-the-road" },
  { theme: "adaptation", angle: "My first road week without the snack routine was rough — now the drive feels shorter without the sugar rollercoaster. My experience, your call.", fits: "on-the-road" },
];
